version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgers
      DB_PASSWORD: postgers
      DB_NAME: bufalo_wallet_db
      DB_HOST: localhost  
      DB_PORT: 5432
      SERVER_PORT: 8080
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgers
      POSTGRES_PASSWORD: postgers
      POSTGRES_DB: bufalo_wallet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
